---
# Non-secret variables that apply to all hosts.
# Ansible will automatically load this file.

# AWS Configuration for the ec2_security_group module
aws_region: "us-east-2" # Or your desired default region
vpc_id: "vpc-08829a6d98471cfc5" # The VPC ID for your EC2 instances

# You can define the security group name here to override the default in the task
security_group_name: "launch-wizard-2"

# For better security, restrict SSH access to a specific IP or range.
# To find your IP, you can run: curl -s ifconfig.me
ssh_allowed_cidr: "3.148.214.53/32" # Replace with your public IP address