---
# Application settings
app_user: "root"
binary_name: "aegong"
app_group: "root"
app_port: 8084
app_dir: "/opt/agent-auditor"
app_version: "v1.0.0" # Or use a tag/commit SHA like "v1.0.1" or "a1b2c3d4e5f6"

# Go settings
go_version: "1.22.5"
go_arch: "amd64"

# Python settings
python_packages:
  - python3
  - python3-pip
  - python3-venv

# Voice config settings (place secrets in vault)
voice_enabled: true
voice_provider: "openai"
voice_key_file_src: "files/default.key" # Path to local encrypted key file
voice_key_file_dest: "{{ app_dir }}/default.key"
voice_key_pass_env_var: "AEGONG_KEY_PASS"
voice_output_dir: "{{ app_dir }}/voice_reports"
voice_default_voice: "alloy"

# Firewall settings
firewall_enabled: true

# AWS settings (only used when running on EC2)
# These can be overridden with extra-vars or group_vars
vpc_id: ""  # This should be provided when running on AWS
security_group_name: "aegong-sg"
aws_region: "us-east-2"
ssh_allowed_cidr: "0.0.0.0/0"  # WARNING: Restrict this in production

# EC2 Instance Management Settings
ec2_instance_tag_name: "agent-auditor"  # The Name tag of your EC2 instance
ec2_wait_timeout: 300  # Timeout in seconds to wait for instance operations
ec2_auto_start: true   # Whether to automatically start the instance before deployment
ec2_auto_stop: true    # Whether to automatically stop the instance after deployment
ec2_ssh_user: "ubuntu"  # SSH user for connecting to the EC2 instance
ec2_ssh_key_file: "~/.ssh/AEGONG.pem"  # Path to the SSH private key file
