---
# Application settings
app_user: "aegong"
app_group: "aegong"
app_dir: "/opt/agent-auditor"
repo_url: "https://github.com/gperry/agent-auditor.git" # Or your fork
app_version: "v1.0.1" # Or use a tag/commit SHA like "v1.0.1" or "a1b2c3d4e5f6"

# Go settings
go_version: "1.22.5"
go_arch: "amd64"

# Python settings
python_packages:
  - python3
  - python3-pip
  - python3-venv

# Voice config settings (place secrets in vault)
voice_enabled: true
voice_provider: "openai"
voice_key_file_src: "files/default.key" # Path to local encrypted key file
voice_key_file_dest: "{{ app_dir }}/default.key"
voice_key_pass_env_var: "AEGONG_KEY_PASS"
voice_output_dir: "{{ app_dir }}/voice_reports"
voice_default_voice: "alloy"
