#!/bin/bash
# set_target_host.sh
# This script determines the machine's IP address and sets it as TARGET_HOST
# It's designed to be run during system startup
#
# Usage: ./set_target_host.sh [env_file_path]
#   env_file_path: Optional path to the .env file (default: /opt/agent-auditor/.env)
#
# The script will:
# 1. Get the machine's public IP address
# 2. If the .env file exists, update or add the TARGET_HOST variable
# 3. If the .env file doesn't exist, create it with TARGET_HOST and default values
# 4. Return the IP address that was set
#
# This script is embedded in the agent-auditor binary and extracted at runtime

# Get the public IP address using AWS metadata service
PUBLIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)

# If we couldn't get the public IP, try to get the local IP
if [ -z "$PUBLIC_IP" ]; then
    # Get the IP address of the default interface
    PUBLIC_IP=$(ip route get 8.8.8.8 | awk '{print $7; exit}')
fi

# If we still don't have an IP, default to localhost
if [ -z "$PUBLIC_IP" ]; then
    PUBLIC_IP="localhost"
fi

# Create or update the environment file
# Use the first argument as the env file path if provided, otherwise use default
ENV_FILE="${1:-/opt/agent-auditor/.env}"

# Check if .env file exists
if [ -f "$ENV_FILE" ]; then
    # File exists, check if TARGET_HOST is already set
    if grep -q "^TARGET_HOST=" "$ENV_FILE"; then
        # Replace existing TARGET_HOST line
        sed -i "s/^TARGET_HOST=.*$/TARGET_HOST=$PUBLIC_IP/" "$ENV_FILE"
        echo "Updated existing TARGET_HOST in $ENV_FILE"
    else
        # Append TARGET_HOST
        echo "TARGET_HOST=$PUBLIC_IP" >> "$ENV_FILE"
        echo "Added TARGET_HOST to existing $ENV_FILE"
    fi
    
    # Check if PROXY_PORT is already set
    if ! grep -q "^PROXY_PORT=" "$ENV_FILE"; then
        echo "PROXY_PORT=80" >> "$ENV_FILE"
    fi
    
    # Check if PORT is already set
    if ! grep -q "^PORT=" "$ENV_FILE"; then
        echo "PORT=8084" >> "$ENV_FILE"
    fi
else
    # File doesn't exist, create it
    echo "# Generated by set_target_host.sh" > "$ENV_FILE"
    echo "TARGET_HOST=$PUBLIC_IP" >> "$ENV_FILE"
    echo "PROXY_PORT=80" >> "$ENV_FILE"
    echo "PORT=8084" >> "$ENV_FILE"
    echo "Created new $ENV_FILE file"
fi

# Log the result
echo "Set TARGET_HOST to $PUBLIC_IP"

# Return the IP address
echo $PUBLIC_IP