---
# Configure firewall rules for Agent Auditor application
# Supports both UFW (Ubuntu) and AWS Security Groups

- name: Check if running on AWS EC2 to determine firewall strategy
  uri:
    url: http://169.254.169.254/latest/meta-data/instance-id
    timeout: 2
  register: aws_instance_check
  ignore_errors: true
  when: firewall_enabled

- name: Install UFW firewall (Ubuntu/Debian)
  package:
    name: ufw
    state: present
  when: 
    - firewall_enabled
    - ansible_os_family == "Debian"
    - not (aws_instance_check is succeeded)
- name: Enable UFW firewall
  ufw:
    state: enabled
    policy: deny
    direction: incoming
  when: 
    - firewall_enabled
    - ansible_os_family == "Debian"
    - not (aws_instance_check is succeeded)
- name: Allow SSH access
  ufw:
    rule: allow
    port: '22'
    proto: tcp
  when: 
    - firewall_enabled
    - ansible_os_family == "Debian"
    - not (aws_instance_check is succeeded)
- name: Allow Agent Auditor application port
  ufw:
    rule: allow
    port: "{{ app_port }}"
    proto: tcp
    comment: "Agent Auditor Web Interface"
  when: 
    - firewall_enabled
    - ansible_os_family == "Debian"
    - not (aws_instance_check is succeeded)
- name: Ensure AWS Security Group is configured for EC2 instance
  amazon.aws.ec2_security_group:
    name: "{{ security_group_name | default('aegong-sg') }}"
    description: "Security group for Agent Auditor"
    vpc_id: "{{ vpc_id }}" # NOTE: This variable must be defined, e.g., via facts or extra-vars
    region: "{{ aws_region | default(ansible_ec2_placement_region, true) | default('us-east-1') }}"
    rules:
      - proto: tcp
        ports: [22]
        cidr_ip: "{{ ssh_allowed_cidr | default('0.0.0.0/0') }}" # WARNING: Restrict this in production
        rule_desc: "Allow SSH"
      - proto: tcp
        ports: ["{{ app_port }}"]
        cidr_ip: "0.0.0.0/0"
        rule_desc: "Allow Agent Auditor Web Interface"
  when:
    - firewall_enabled
    - aws_instance_check is succeeded

- name: Display AWS instance information
  debug:
    msg: |
      AWS EC2 Instance Detected!
      =========================
      
      Instance ID: {{ aws_instance_check.content | default('Unable to retrieve') }}
      
      Make sure your EC2 instance has the correct Security Group attached.
      You can check this in the AWS Console under EC2 > Instances > Security Groups
      
      To access your Agent Auditor application:
      http://{{ ansible_default_ipv4.address }}:{{ app_port }}
      
      Or if you have an Elastic IP or domain:
      http://YOUR_DOMAIN_OR_EIP:{{ app_port }}
  when: 
    - firewall_enabled
    - aws_instance_check is succeeded

- name: Display local firewall status
  debug:
    msg: |
      Local Firewall Configuration Complete
      ====================================
      
      UFW Status: Enabled
      Allowed Ports:
      - SSH (22/tcp)
      - Agent Auditor ({{ app_port }}/tcp)
      
      Access your application at:
      http://{{ ansible_default_ipv4.address }}:{{ app_port }}
  when: 
    - firewall_enabled
    - ansible_os_family == "Debian"
    - not (aws_instance_check is succeeded)
