---
- name: Copy local binary to server
  copy:
    src: "../../../{{ binary_name }}" # Path relative to the playbook file
    dest: "{{ app_dir }}/{{ binary_name }}"
    owner: root
    group: root
    mode: '0755' # Make it executable
    
- name: Ensure binary is executable
  file:
    path: "{{ app_dir }}/{{ binary_name }}"
    mode: '0755'
    owner: root
    group: root
    attributes: "+x"

- name: Copy requirements.txt to server
  copy:
    src: "../../../requirements.txt"
    dest: "{{ app_dir }}/requirements.txt"
    owner: root
    group: root
    mode: '0644'

- name: Install Python dependencies
  pip:
    requirements: "{{ app_dir }}/requirements.txt"
    virtualenv: "{{ app_dir }}/venv"
    virtualenv_command: python3 -m venv

- name: Create required directories
  file:
    path: "{{ app_dir }}/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - uploads
    - reports
    - voice_reports
    - logs     # Add logs directory for audit logs

- name: Create empty audit log file with correct permissions
  file:
    path: "{{ app_dir }}/aegong_audit.log"
    state: touch
    owner: root
    group: root
    mode: '0644'
    
- name: Ensure application directory and contents are readable by root
  file:
    path: "{{ app_dir }}"
    state: directory
    mode: '0755'
    recurse: yes

- name: Create .env file with application configuration
  copy:
    dest: "{{ app_dir }}/.env"
    content: |
      # Generated by Ansible
      TARGET_HOST={{ inventory_hostname }}
    
      PORT=8084
      # Add domain name for SSL validation
      DOMAIN_NAME={% if use_domain_for_ssl and domain_name is defined %}{{ domain_name }}{% else %}{{ inventory_hostname }}{% endif %}
      
      # IMPORTANT: PROXY_PORT is intentionally not defined here
      # NGINX handles all HTTP/HTTPS routing on ports 80/443 to the application on port 8084
    owner: root
    group: root
    mode: '0644'

- name: Display .env file content
  command: cat {{ app_dir }}/.env
  register: env_file_content
  changed_when: false

- name: Show .env file content
  debug:
    msg: "{{ env_file_content.stdout_lines }}"

- name: Copy encrypted key file to server
  copy:
    src: "{{ voice_key_file_src }}"
    dest: "{{ voice_key_file_dest }}"
    owner: root
    group: root
    mode: '0600' # Restrictive permissions
  when: voice_enabled

- name: Configure voice_config.json from template
  template:
    src: voice_config.json.j2
    dest: "{{ app_dir }}/voice_config.json"
    owner: root
    group: root
    mode: '0644'
  when: voice_enabled

- name: Copy systemd service file
  template:
    src: aegong.service.j2
    dest: "/etc/systemd/system/{{ binary_name }}.service"
    owner: root
    group: root
    mode: '0644'


- name: Enable and start the {{ binary_name }} service
  systemd:
    name: "{{ binary_name }}"
    state: started
    enabled: true
    daemon_reload: true

- name: Wait for the application to generate necessary files (10 seconds)
  wait_for:
    timeout: 10
  become: false

- name: Display service logs to check for file generation issues
  shell: journalctl -u {{ binary_name }} -n 20
  register: service_logs
  changed_when: false

- name: Show service logs
  debug:
    msg: "{{ service_logs.stdout_lines }}"

- name: Check if default.key exists
  stat:
    path: "{{ app_dir }}/default.key"
  register: default_key_stat
  become: true

- name: Ensure default.key has correct permissions if it exists
  file:
    path: "{{ app_dir }}/default.key"
    owner: root
    group: root
    mode: '0644'  # Readable by root
  when: default_key_stat.stat.exists
  become: true

- name: Check if set_target_host.sh exists
  stat:
    path: "{{ app_dir }}/scripts/set_target_host.sh"
  register: set_target_host_stat
  become: true

- name: Ensure set_target_host.sh has correct permissions if it exists
  file:
    path: "{{ app_dir }}/scripts/set_target_host.sh"
    owner: root
    group: root
    mode: '0755'  # Executable
  when: set_target_host_stat.stat.exists
  become: true


