---
# tasks file for agent_auditor

- name: Include prerequisites task
  include_tasks: prereq.yml

- name: Create aegong user
  user:
    name: aegong
    system: yes
    shell: /usr/sbin/nologin

- name: Set up Python environment
  include_tasks: setup_python.yml

- name: Include setup tasks
  include_tasks: setup_go.yml

- name: Ensure application directory exists
  file:
    path: /opt/agent-auditor
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Include application deployment tasks
  include_tasks: deploy_app.yml

- name: Configure NGINX as reverse proxy
  include_tasks: configure_nginx.yml

- name: Include firewall configuration tasks
  include_tasks: configure_firewall.yml

- name: Include health check tasks
  include_tasks: health_check.yml
  ignore_errors: true
