---
# tasks file for agent_auditor prerequisites

- name: Ensure required packages are installed
  ansible.builtin.package:
    name:
      - acl
      - nginx
    state: present
  become: true
  become_user: root

# User management removed - application now runs as root as configured

- name: Check if cgroups v2 is in use
  stat:
    path: /sys/fs/cgroup/cgroup.controllers
  register: cgroups_v2_check

- name: Set cgroups version fact
  set_fact:
    using_cgroups_v2: "{{ cgroups_v2_check.stat.exists }}"

- name: Create root cgroup directory for cgroups v2
  block:
    - file:
        path: /sys/fs/cgroup/aegong
        state: directory
        mode: '0755'
        owner: root
        group: root
  when: using_cgroups_v2
  ignore_errors: true

- name: Create root cgroup directories for cgroups v1
  block:
    - file:
        path: "/sys/fs/cgroup/{{ item }}/aegong"
        state: directory
        mode: '0755'
        owner: root
        group: root
      loop:
        - memory
        - cpu
        - cpuacct
  when: not using_cgroups_v2
  ignore_errors: true

# No longer need to add aegong user to systemd-journal group as we're using root for everything