---
# tasks file for setting up Python for agent_auditor

- name: Ensure Python system packages for venv are installed
  ansible.builtin.package:
    name:
      - python3-pip
      - python3-venv
    state: present
  become: true
  become_user: root

- name: Create virtualenv and install Python dependencies
  ansible.builtin.pip:
    requirements: "{{ app_dir }}/requirements.txt"
    virtualenv: "{{ app_dir }}/venv"
    virtualenv_command: python3 -m venv
  become: true
  become_user: root
