---
# EC2 Instance Management and Deployment Playbook
# This playbook implements a cost-saving strategy by:
# 1. Finding and starting the EC2 instance
# 2. Deploying the application
# 3. Ensuring the instance is stopped after deployment (success or failure)

- name: Manage EC2 Instance Lifecycle
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - roles/agent_auditor/defaults/main.yml
    - group_vars/all/main.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3
    aws_region: "{{ aws_region }}"
    instance_tag_name: "{{ ec2_instance_tag_name }}"
    wait_for_instance_timeout: "{{ ec2_wait_timeout }}"
    force_update: "{{ force_update | default(false) }}"
  
  tasks:
    - name: Skip EC2 management if auto-start is disabled and not forced
      meta: end_play
      when: not ec2_auto_start | bool and not force_update | bool
      tags: [ec2_management]
      
    - name: Set instance ID from parameter or find by tag
      block:
        - name: Debug EC2 instance ID parameter
          debug:
            msg: "EC2 instance ID parameter: '{{ ec2_instance_id | default('not provided') }}'"
          
        - name: Use provided EC2 instance ID if available
          set_fact:
            instance_id: "{{ ec2_instance_id }}"
          when: ec2_instance_id is defined and ec2_instance_id != ""
          
        - name: Debug instance ID after parameter check
          debug:
            msg: "Instance ID after parameter check: '{{ instance_id | default('not set') }}'"
          
        - name: Find EC2 instance by tag if no instance ID provided
          amazon.aws.ec2_instance_info:
            region: "{{ aws_region }}"
            filters:
              "tag:Name": "{{ instance_tag_name }}"
          register: ec2_info
          when: instance_id is not defined
          
        - name: Debug EC2 info when searching by tag
          debug:
            msg: "EC2 info when searching by tag: {{ ec2_info | default('not searched') }}"
          when: ec2_info is defined
          
        - name: Verify instance was found when searching by tag
          fail:
            msg: "No EC2 instance found with tag Name:{{ instance_tag_name }}"
          when: 
            - instance_id is not defined
            - ec2_info.instances | length == 0
            
        - name: Set instance ID variable from tag search
          set_fact:
            instance_id: "{{ ec2_info.instances[0].instance_id }}"
          when: instance_id is not defined and ec2_info.instances | length > 0
          
        - name: Debug final instance ID
          debug:
            msg: "Final instance ID: '{{ instance_id | default('not set') }}'"
      when: ec2_auto_start | bool or force_update | bool
      tags: [ec2_management]
        
    - name: Start EC2 instance
      amazon.aws.ec2_instance:
        instance_ids: "{{ instance_id }}"
        region: "{{ aws_region }}"
        state: running
        wait: yes
        wait_timeout: "{{ wait_for_instance_timeout }}"
      register: started_instance
      when: (ec2_auto_start | bool or force_update | bool) and instance_id is defined
      tags: [ec2_management]
      
    - name: Get instance public IP
      amazon.aws.ec2_instance_info:
        region: "{{ aws_region }}"
        instance_ids: "{{ instance_id }}"
      register: running_instance_info
      when: (ec2_auto_start | bool or force_update | bool) and instance_id is defined
      tags: [ec2_management, update_dns]
      
    - name: Set instance IP variable
      set_fact:
        instance_ip: "{{ running_instance_info.instances[0].public_ip_address }}"
      when: (ec2_auto_start | bool or force_update | bool) and running_instance_info is defined
      tags: [ec2_management, update_dns]
        
    - name: Wait for SSH to become available
      wait_for:
        host: "{{ instance_ip }}"
        port: 22
        delay: 10
        timeout: 300
      delegate_to: localhost
      when: (ec2_auto_start | bool or force_update | bool) and instance_ip is defined
      tags: [ec2_management]
      
    - name: Update inventory with dynamic IP
      add_host:
        name: "{{ instance_ip }}"
        groups: aegong_dynamic
        ansible_user: "{{ ec2_ssh_user }}"
        ansible_ssh_private_key_file: "{{ ec2_ssh_key_file }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
      when: (ec2_auto_start | bool or force_update | bool) and instance_ip is defined
      tags: [ec2_management]
        
    - name: Debug SSH configuration
      debug:
        msg: 
          - "SSH User: {{ ec2_ssh_user }}"
          - "SSH Key File: {{ ec2_ssh_key_file }}"
          - "Target IP: {{ instance_ip }}"
      when: (ec2_auto_start | bool or force_update | bool) and instance_ip is defined
      tags: [ec2_management]
        
    - name: Display instance information
      debug:
        msg: "EC2 instance {{ instance_id }} is now running at {{ instance_ip }}"
      when: (ec2_auto_start | bool or force_update | bool) and instance_id is defined and instance_ip is defined
      tags: [ec2_management, update_dns]
        
    - name: Update configuration files with new IP address
      shell: "{{ playbook_dir }}/../scripts/update_ec2_ip.sh {{ instance_ip }}"
      args:
        chdir: "{{ playbook_dir }}/.."
      when: (ec2_auto_start | bool or force_update | bool) and instance_ip is defined
      delegate_to: localhost
      tags: [ec2_management, update_dns]

# Deploy to dynamic IP if auto-start is enabled
- name: Deploy Agent Auditor Application (Dynamic IP)
  hosts: aegong_dynamic
  become: true
  gather_facts: true
  roles:
    - agent_auditor
  vars:
    ansible_python_interpreter: /usr/bin/python3
    deploy_condition: "{{ ec2_auto_start | bool and hostvars['localhost']['instance_ip'] is defined }}"
  tasks:
    - meta: end_play
      when: not deploy_condition

# Deploy to static inventory if auto-start is disabled
# This play is now disabled as we're using the dynamic IP approach
- name: Deploy Agent Auditor Application (Static IP)
  hosts: aegong_servers
  become: true
  gather_facts: true
  roles:
    - agent_auditor
  vars:
    deploy_condition: false  # Always skip this play as we're using dynamic IP
  tasks:
    - meta: end_play
      when: not deploy_condition

- name: Stop EC2 instance after deployment
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - roles/agent_auditor/defaults/main.yml
    - group_vars/all/main.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3
    aws_region: "{{ aws_region }}"
    instance_id: "{{ hostvars['localhost']['instance_id'] | default(None) }}"
    wait_for_instance_timeout: "{{ ec2_wait_timeout }}"
    force_update: "{{ force_update | default(false) }}"
  
  tasks:
    - name: Skip if auto-stop is disabled or instance_id is not defined
      meta: end_play
      when: (not ec2_auto_stop | bool and not force_update | bool) or instance_id is none
      tags: [ec2_management]
      
    - name: Skip stopping EC2 if this is a DNS-only update
      meta: end_play
      when: force_update | bool and dns_only_update | default(false) | bool
      tags: [ec2_management]
      
    - name: Stop EC2 instance
      amazon.aws.ec2_instance:
        instance_ids: "{{ instance_id }}"
        region: "{{ aws_region }}"
        state: stopped
        wait: yes
        wait_timeout: "{{ wait_for_instance_timeout }}"
      register: stopped_instance
      when: (ec2_auto_stop | bool or force_update | bool) and instance_id is not none
      tags: [ec2_management]
      
    - name: Confirm instance is stopped
      debug:
        msg: "EC2 instance {{ instance_id }} has been stopped successfully"
      when: (ec2_auto_stop | bool or force_update | bool) and stopped_instance is defined
      tags: [ec2_management]