---
- name: Restart {{ binary_name }} service
  systemd:
    name: "{{ binary_name }}"
    state: restarted
  notify: Set permissions after service restart

- name: Set permissions after service restart
  block:
    - name: Wait for files to be generated (5 seconds)
      wait_for:
        timeout: 5
      delegate_to: localhost
      
    - name: Check if default.key exists
      stat:
        path: "{{ app_dir }}/default.key"
      register: default_key_stat
    
    - name: Ensure default.key has correct permissions if it exists
      file:
        path: "{{ app_dir }}/default.key"
        owner: root
        group: root
        mode: '0644'  # Readable by root
      when: default_key_stat.stat.exists
    
    - name: Check if set_target_host.sh exists
      stat:
        path: "{{ app_dir }}/scripts/set_target_host.sh"
      register: set_target_host_stat
    
    - name: Ensure set_target_host.sh has correct permissions if it exists
      file:
        path: "{{ app_dir }}/scripts/set_target_host.sh"
        owner: root
        group: root
        mode: '0755'  # Executable
      when: set_target_host_stat.stat.exists

