---
- name: Restart {{ binary_name }} service
  systemd:
    name: "{{ binary_name }}"
    state: restarted

- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: Set permissions after service restart
  block:
    - name: Wait for files to be generated (5 seconds)
      wait_for:
        timeout: 5
      become: false
      
    - name: Check if default.key exists
      stat:
        path: "{{ app_dir }}/default.key"
      register: default_key_stat
      become: true
    
    - name: Ensure default.key has correct permissions if it exists
      file:
        path: "{{ app_dir }}/default.key"
        owner: root
        group: root
        mode: '0644'  # Readable by root
      when: default_key_stat.stat.exists
      become: true

