name: Update Cloudflare DNS

on:
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Force update even if EC2 is already running'
        required: false
        type: boolean

jobs:
  update-dns:
    name: Update Cloudflare DNS with EC2 IP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install or update AWS CLI v2
        run: |
          # Check if AWS CLI is already installed
          if command -v aws &> /dev/null && aws --version | grep -q "aws-cli/2"; then
            echo "AWS CLI v2 is already installed. Updating..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -q awscliv2.zip
            sudo ./aws/install --update
          else
            echo "Installing AWS CLI v2..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -q awscliv2.zip
            sudo ./aws/install
          fi
          aws --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Ansible and required dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible sshpass python3-boto3 python3-botocore
          
          # Find the Ansible Python interpreter path
          ANSIBLE_PYTHON_PATH=$(ansible --version | grep "python version" | awk '{print $4}')
          echo "Ansible is using Python interpreter: $ANSIBLE_PYTHON_PATH"
          
          # Install Python dependencies in the Ansible Python environment
          if [[ -n "$ANSIBLE_PYTHON_PATH" ]]; then
            echo "Installing boto3 and botocore for Ansible's Python interpreter"
            sudo -H $ANSIBLE_PYTHON_PATH -m pip install boto3 botocore
          else
            echo "Installing boto3 and botocore system-wide"
            sudo pip3 install boto3 botocore
          fi

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Create .env file with Cloudflare credentials
        run: |
          cat > .env << EOF
          CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID=${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_RECORD_NAME=${{ secrets.CLOUDFLARE_RECORD_NAME }}
          EOF

      - name: Run Ansible playbook to start EC2 and update DNS
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          FORCE_UPDATE: ${{ github.event.inputs.force_update }}
          EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
          ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3
        run: |
          echo "$ANSIBLE_VAULT_PASSWORD" > .vault_pass
          
          # Run only the EC2 management and IP update parts of the playbook
          PYTHONPATH=/usr/lib/python3/dist-packages ansible-playbook ansible/playbook.yml --vault-password-file .vault_pass --tags "ec2_management,update_dns" -e "force_update=$FORCE_UPDATE ec2_instance_id=$EC2_INSTANCE_ID ansible_python_interpreter=$ANSIBLE_PYTHON_INTERPRETER"
          
          # Display debug information
          echo "Using EC2 instance ID: $EC2_INSTANCE_ID"
          echo "Using Python interpreter: $ANSIBLE_PYTHON_INTERPRETER"
          
          rm .vault_pass

      - name: Clean up
        if: always()
        run: |
          rm -rf ~/.ssh
          rm -f .env